### ISSUE TITLE
Get some warning while compiling nms

### ISSUE THREAD

**Issue by Suujy** [NVlabs/planercnn#11]
_**warning**_: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* mask_flat = THCudaLongTensor_data(state, mask);
                                   ^
/home/sujunyu/planercnn-master/nms/src/nms_cuda.c:37:40: **_warning_**: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long * mask_cpu_flat = THLongTensor_data(mask_cpu);
                                        ^
/home/sujunyu/planercnn-master/nms/src/nms_cuda.c:40:39: **_warning_**: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* remv_cpu_flat = THLongTensor_data(remv_cpu);
                                       ^
/home/sujunyu/planercnn-master/nms/src/nms_cuda.c:23:7: **_warning_**: unused variable 'boxes_dim' [-Wunused-variable]
   int boxes_dim = THCudaTensor_size(state, boxes, 1);

**These lead to the problem " can't find nms.gpu_nms " while running train_planeRCNN.  I assume it is due to the unsuccessfully compilation of nms.** 

**I've already used docker with gcc version 5.4, cuda 9.0. Seems like the nms code has a problem?**

**Comment by Suujy** [comment]
solved by modifying **unsigned long long** into **int64_t**

**Comment by carbondriller** [comment]
@Suujy this did work for me

**Comment by art-programmer** [comment]
Could you check the compiled files under nms build folder? I'd recommend asking the question on the original PyTorch repo, https://github.com/multimodallearning/pytorch-mask-rcnn.
