### ISSUE TITLE
Any pre-processed data for training and test

### ISSUE THREAD

**Issue by yangengt123** [NVlabs/planercnn#2]
Hi,
Thanks for sharing the code of your great work. 

I am trying to run the training code, but I found the whole ScanNet dataset is rather than large. May I ask if it is necessary to download all the .sens from the dataset? Is it possible to get access to your per-processed data, or to train the network with part of this dataset? 

BTW, a small contribution, if any one uses Cuda 9 + RTX 2080 GPU, the arch should be ```sm_70``` for the nvcc compilement. A link for other gpu types: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by art-programmer** [comment]
We are processing that. I will keep you updated. And thank you for the pointer!

**Comment by yangengt123** [comment]
Hi, I was trying to run the training code, and I found in https://github.com/NVlabs/planercnn/blob/557583f1e005409e960e159143ca17b033413a09/datasets/plane_dataset.py#L94 it asks a .tsv file named ```scannetv2-labels.combined.tsv```. 
May I ask where I can get access to this file?

**Comment by art-programmer** [comment]
They are from the original ScanNet dataset. You need to download the data and uncompress the .sens file (maybe delete the .sens file after uncompression to save space).

**Comment by yangengt123** [comment]
Thanks.  
Just for someone else who is not familiar with ScanNet dataset, to get thees files, please use the argument ```--type .sens .txt``` and ```--label_map``` during download. 

By the way, how can I run the training with multiple gpu? I cannot find any line contain the function ```torch.nn.DataParallel(model).cuda()```, which I usually use for multi-gpu training. I tried to uncommment  
https://github.com/NVlabs/planercnn/blob/41a0f631bcf7c353faf8291e950cfb713cf07356/config.py#L360
but it seems does not work.

**Comment by dreamPoet** [comment]
Sorry but is there any way we can run ScanNet original sens reader.py for all sens files scattered in different scene files? It looks like I cannot move all .sens file into one directory as it is important to map to corresponding annotations in later merging operation.

**Comment by yangengt123** [comment]
Hi @dreamPoet , I just simply set the ```--filename``` as the ```path/to/Scannet_data/scans/```, and it seems works well for me.

**Comment by dreamPoet** [comment]
Hi @yangengt123, do you simply use `--filename path/to/scans/ `？ I get the error ` Is a directory: '../../ScanNet/scans/'`. If I use `../../ScanNet/scans/*/*.sens`, it gives error `unrecognized arguments: scans/scene0000_01/scene0000_01.sens`...

**Comment by yangengt123** [comment]
Yeah, the only difference is  I used absolute path, something like ```/hdd/Scannet_data/scans/```, and I did not meet any trouble to sparse it. But I think it is always possible to look into the ```SensorData.py``` to check which path the ```load``` function is using.

**Comment by dreamPoet** [comment]
> Thanks.
> Just for someone else who is not familiar with ScanNet dataset, to get thees files, please use the argument `--type .sens .txt` and `--label_map` during download.
> 
> By the way, how can I run the training with multiple gpu? I cannot find any line contain the function `torch.nn.DataParallel(model).cuda()`, which I usually use for multi-gpu training. I tried to uncommment
> 
> https://github.com/NVlabs/planercnn/blob/41a0f631bcf7c353faf8291e950cfb713cf07356/config.py#L360
> 
> but it seems does not work as well.

Thank you, but have you solve the problem of multi-GPU training now? I meet the same problem.

**Comment by dreamPoet** [comment]
By the way I use srun with gpu:8 and -n8 as bash command.

**Comment by dreamPoet** [comment]
And there are three parameters related to batch size, one in config, one in option, and one for dataset loader...Frankly, I am a bit of confused...

**Comment by wullish** [comment]
@dreamPoet did you solve the .sens files extraction problem using reader.py? I'm in the exactly same problem. Any idea?

Best.

**Comment by wullish** [comment]
Well, I could solve it using python 2.7 but calling one .sens file per once. And dont forget about the **reader.py** options arguments such as **--export_depth_images**, **--export_color_images**, etc.

**Comment by yangengt123** [comment]
That is right, I use python2.7. Maybe this is the reason I did not meet any problem. 

By the way, may I ask if you can still download the data from ScanNet recently? I tried to download the data to a new server but it seems my download script cannot work.

**Comment by wullish** [comment]
Ah thanks. 
Yes, I've downloaded the whole data last week. Maybe they've changed the urls. I think you can contact scannet@googlegroups.com and ask them about the script.

**Comment by yangengt123** [comment]
yeah, maybe I should. Thanks.
I will close this issue now. 
Please let me know if any pre-processed data become available.
