### ISSUE TITLE
Plane class name

### ISSUE THREAD

**Issue by amitshaked** [NVlabs/planercnn#20]
Hey, I can see that you output the class index of each plane, but I can't find the actual names of the classes. Could you please refer me to the id-to-name mapping?

Thanks a lot!

**Comment by art-programmer** [comment]
Actually, there's no semantic here (no category class). The class id refers to the anchor normal the plane is assigned to. The final 3D normal prediction equals the summation of the anchor normal and the predicted residual. Everything is geometry here. Anchor normals are stored in anchor_planes_N.npy as metadata.

**Comment by amitshaked** [comment]
Got it, thanks!
