### ISSUE TITLE
 undefined symbol: __cudaRegisterFatBinaryEnd 

### ISSUE THREAD

**Issue by MrYelameli** [NVlabs/planercnn#34]
Cuda version - 10.1 
pytorch version - 0.4.1 
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

How to resolve this?

**Comment by cgarg-tud** [comment]
I get this error as well

**Comment by MitchellUsayiwevu** [comment]
downgrade Cuda to a version less than Cuda 10. I resolved the issue by using Cuda 9.0

**Comment by jaeishin** [comment]
I got this exact same error!
downgrade cuda 10 -> cuda 9.0 will help

**Comment by henbucuoshanghai** [comment]
how about 9.1? @jaeishin

**Comment by elliestath** [comment]
hey, I am using Cuda 9.0 and GCC 5.4, python 3.7.6 on Ubuntu 18.04 with pytorch 0.4.1 (tried also pytorch 0.4.0) but still getting this error when trying to run evaluate.py

compiling nms give error `PermissionError: [Errno 1] Operation not permitted: '/opt/nms/_ext/nms/_nms.so'`

**Comment by jaeishin** [comment]
@henbucuoshanghai sorry for late reply 
i'm not sure about cuda 9.1... at that time, we just solved our problem by downgrading cuda to 9.0

**Comment by elliestath** [comment]
right, I use cuda 9.0.
I also checked a docker image on dockerhub but same issue there
