### ISSUE TITLE
Checkpoint not matching command provided in readme

### ISSUE THREAD

**Issue by ajithvcoder** [NVlabs/planercnn#52]
Hi @art-programmer 

I am trying to run '!python evaluate.py --methods=f --suffix=wraping_refine --dataset=inference --customDataFolder=example_images'

After setting up env, building nms and roi align . its giving me below error i think the checkpoint is not matching the model. Could you give correct command or checkpoint

![eval_rcnn](https://user-images.githubusercontent.com/8075112/96346604-5327a280-10ba-11eb-8aac-e8da926052b8.PNG)

**Comment by ajithvcoder** [comment]
it was matching thanks

**Comment by FranciscoFavela** [comment]
hello i have the same error Can you tell me how you solved this problem?
