### ISSUE TITLE
How to generate 3D model from the output of refine segmentations

### ISSUE THREAD

**Issue by ajithvcoder** [NVlabs/planercnn#53]
Hi @art-programmer 

I have got results from this command 
```python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images```

![snap_results](https://user-images.githubusercontent.com/8075112/97103020-1e29da00-16d0-11eb-8163-f12e23eaaeba.PNG)

How should i use it to generate 3D mesh ?

**Comment by ajithvcoder** [comment]
![planes](https://user-images.githubusercontent.com/8075112/97071089-3ed43000-15fb-11eb-928a-316dbc635b83.PNG)

i have 3 images in this but i dont know to generate the 4th one

**Comment by Karthikaddagadderamesh** [comment]
@ajithvallabai  I am also looking for the 3D representation code..were you successful?

**Comment by ajithvcoder** [comment]
@Karthikaddagadderamesh  you can take this code https://github.com/ajithvallabai/planercnn_with_adf/blob/master/genrate_3dmodel/write_ply_planenet.py . in case if you are successful let me know.

**Comment by ajithvcoder** [comment]
its resolved , code to generate 3d model is in visuvalize_util.py
