### ISSUE TITLE
how can i get the normal of planes  for each frame extracted from /scene_id/scene_id.sens?

### ISSUE THREAD

**Issue by Hui-Yao** [NVlabs/planercnn#54]
hello!  thanks for your impressive work of this project.

after running parse.py,  i got three files:
annotation/segmentation/ *.png :  the planr segmentation of each frame
annotation/planes.npy : the global normal for all the planes in the scene
annotation/planes.ply : the 3D mesh model of the scene, and i can open it with meshlab

I think these files should be the correct output of parse.py .

for now, i want to get the normal of planes of each frame extracted from /scene_id/scene_id.sens using the official reader,
but i have saw  the document of  both PlaneNet and PlaneRcnn, i can`t figure out it.

could you tell me how to solve it ? 
thank  a lot.

By the way : welcome to contact me at   im_huiyao@163.com  , if anyone wanna dicuss problems of PlaneNet and PlaneRcnn.

![0](https://user-images.githubusercontent.com/52377012/96606218-9cc9f480-1329-11eb-9dda-9c32371b6b05.png)

**Comment by ajithvcoder** [comment]
@Hui-Yao  mailed you, my id is inocajith21.5@gmail.com

**Comment by ajithvcoder** [comment]
@Hui-Yao  you can use this repo https://github.com/chaowang15/RGBDPlaneDetection for getting normals
