### ISSUE TITLE
Pretrained model links are not working

### ISSUE THREAD

**Issue by ajithvcoder** [NVlabs/planercnn#55]
HI @art-programmer ,

The pretrained model links are not working, could you please check it .

Thanks,
Ajith

**Comment by ajithvcoder** [comment]
now its up thanks for it

**Comment by lowe2011** [comment]
Hi @ajithvallabai ,
I met the same problem with you, the pretrained model links are not working now again, if you have solved the problem, can you please provide new links for downloading it?

Thanks,
Lowe

**Comment by ajithvcoder** [comment]
@lowe2011  you can use this link for pretrained mode download https://drive.google.com/file/d/1o2wZG0swF-HImZbQGPC7cHONkCThFVQZ/view?usp=sharing
