### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../Data/ScanNet//scannetv2-labels.combined.tsv'

### ISSUE THREAD

**Issue by MaFengWoXiaoZi** [NVlabs/planercnn#57]
Excuse me, I don't understand why a "Data" folder appears. The entire ScanNet dataset is so big that I just choose part of it. I want to train my model, but there was this mistake. Please help me, what should I do. Really thank you. 
![Screenshot from 2020-10-30 06-34-33](https://user-images.githubusercontent.com/16892030/97695195-0c528900-1a7a-11eb-8141-260013ee2da3.png)

**Comment by ajithvcoder** [comment]
@MaFengWoXiaoZi  u can download few scenes alone. Also labels.combined.tsv u can download seperately . u can read the scannet mail sent to u

**Comment by MaFengWoXiaoZi** [comment]
@ajithvallabai I see, really thank you.

**Comment by ajithvcoder** [comment]
@MaFengWoXiaoZi  please close this issue

**Comment by Karthikaddagadderamesh** [comment]
@ajithvallabai in how many days did you get access to the scannet dataset and were you able to train on that.?

**Comment by ajithvcoder** [comment]
@Karthikaddagadderamesh  i have mailed you
