### ISSUE TITLE
Pretrained model links are not working now

### ISSUE THREAD

**Issue by lowe2011** [NVlabs/planercnn#58]
HI @art-programmer 

The pretrained model links are not working, could you please update it ？ The dropbox link is 404 now.

Thanks,
lowe

**Comment by ajithvcoder** [comment]
pretrained model - https://drive.google.com/file/d/1o2wZG0swF-HImZbQGPC7cHONkCThFVQZ/view?usp=sharing .      Dont close it i need annotations also for trianing but its not up. @art-programmer

**Comment by lowe2011** [comment]
ajith, thanks！
