### ISSUE TITLE
Unable to compile NMS and ROI-Align on RTX 3080

### ISSUE THREAD

**Issue by bundle-adjuster** [NVlabs/planercnn#63]
Hello team, I was trying to reproduce this on my system with a RTX 3080. But it is failing to compile with arch = sm_86 which is the compute architecture for Ampere based GPUs. Given that is there a way I can get this to work?

**Comment by bundle-adjuster** [comment]
nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_86 

Fails due to CUDA 9.0 not supporting it. And the pipeline doesn't build on Higher CUDA versions.

**Comment by SJingjia** [comment]
> nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_86
> 
> Fails due to CUDA 9.0 not supporting it. And the pipeline doesn't build on Higher CUDA versions.

using arch=sm_61 with RTX 3080Ti can work

**Comment by bundle-adjuster** [comment]
> > nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_86
> > Fails due to CUDA 9.0 not supporting it. And the pipeline doesn't build on Higher CUDA versions.
> 
> using arch=sm_61 with RTX 3080Ti can work

It will work, but it will be extremely slow in data loading. Is there no work around for the same?
